import {useEffect,useMemo,useState} from 'react'
import {movies} from './movies'
const V=new Set(['A','E','I','O','U']), C='BCDFGHJKLMNPQRSTVWXYZ'.split(''), N=9
type R={id:number;title:string;score:number;solved:boolean}
function ids(){let p=[...movies],a:number[]=[];while(a.length<5){let i=Math.floor(Math.random()*p.length);a.push(p[i].id);p.splice(i,1)}return a}
function decode(x:string|null){if(!x)return null;let a=x.split('-').map(Number);return a.length===5&&a.every(i=>movies.some(m=>m.id===i))?a:null}
function win(t:string,g:Set<string>){return[...t].every(c=>!/[A-Za-z]/.test(c)||V.has(c.toUpperCase())||g.has(c.toUpperCase()))}
export function App(){
 const challenge=useMemo(()=>decode(new URLSearchParams(location.search).get('challenge')),[])
 const [game,setGame]=useState({movieIds:challenge??ids(),round:0,guessed:[],wrong:0,results:[] as R[],done:false})
 const [copied,setCopied]=useState(false), movie=movies.find(m=>m.id===game.movieIds[game.round])!, guessed=new Set(game.guessed)
 const score=Math.max(0,N-game.wrong), solved=win(movie.title,guessed), lost=!solved&&game.wrong>=N
 const total=game.results.reduce((s,r)=>s+r.score,0)
 useEffect(()=>{if(game.done||(!solved&&!lost))return;let t=setTimeout(()=>setGame(g=>{let r={id:movie.id,title:movie.title,score:solved?score:0,solved},results=[...g.results,r];return g.round===4?{...g,results,done:true}:{...g,results,round:g.round+1,guessed:[],wrong:0}}),solved?800:1200);return()=>clearTimeout(t)},[solved,lost,game.done,movie,score])
 function pick(l:string){if(solved||lost||game.guessed.includes(l))return;setGame(g=>({...g,guessed:[...g.guessed,l],wrong:g.wrong+(movie.title.toUpperCase().includes(l)?0:1)}))}
 function restart(){history.replaceState({},'',location.pathname);setGame({movieIds:ids(),round:0,guessed:[],wrong:0,results:[],done:false})}
 async function share(){let u=`${location.origin}${location.pathname}?challenge=${game.movieIds.join('-')}`,t=`🎬 I scored ${total}/45 on Filmy Guess! Think you can beat me?\\n${u}`;try{if(navigator.share)await navigator.share({title:'Filmy Guess',text:t});else{await navigator.clipboard.writeText(t);setCopied(true);setTimeout(()=>setCopied(false),1500)}}catch{}}
 if(game.done)return <main><section className="shell results"><div className="logo">FILMY <b>GUESS</b></div><div className="hero">🏆<h1>Game Over!</h1><p>Five movies. One final tally.</p></div><div className="card score"><strong>{total}<small>/45</small></strong><label>TOTAL SCORE</label>{game.results.map((r,i)=><div className="row" key={i}><span>Movie {i+1}</span><b>{r.solved?r.score:'MISS'}</b></div>)}<div className="sq">{game.results.map((r,i)=><span key={i}>{r.solved?(r.score>=7?'🟩':r.score>=4?'🟨':'🟧'):'🟥'}</span>)}</div><p>{game.results.filter(r=>r.solved).length}/5 movies guessed</p></div><div className="actions"><button className="primary" onClick={share}>↗ {copied?'Copied!':'Challenge a Friend'}</button><button onClick={restart}>Play Again</button></div></section></main>
 return <main><section className="shell"><header><div className="logo">FILMY <b>GUESS</b></div><div className="pill">MOVIE {game.round+1} / 5</div></header><div className="progress"><i style={{width:`${game.round*25}%`}}/></div><section className="card game"><div className="top"><span>Guess the Bollywood movie</span><b>★ {score}</b></div><div className="bollywood">{'BOLLYWOOD'.split('').map((x,i)=><span className={i>=score?'cut':''} key={i}>{x}</span>)}</div><div className="title">{[...movie.title].map((c,i)=>/[A-Za-z]/.test(c)?<span key={i}>{V.has(c.toUpperCase())||guessed.has(c.toUpperCase())?c:<em>_</em>}</span>:<span key={i}>{c}</span>)}</div><p className="hint">{solved?'🎉 Nailed it!':lost?`The movie was ${movie.title}`:'Vowels are free. Pick a consonant.'}</p><div className="keys">{C.map(l=><button key={l} disabled={game.guessed.includes(l)||solved||lost} className={game.guessed.includes(l)?(movie.title.toUpperCase().includes(l)?'good':'bad'):''} onClick={()=>pick(l)}>{l}</button>)}</div></section><div className="rule">🎬 <span><b>9 chances.</b> Every wrong consonant crosses out one letter of BOLLYWOOD.</span></div><footer><button onClick={restart}>↻ New Game</button><span>Best of 5</span></footer></section></main>
}